name: "Deploy"

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Print variable
        run: echo "This is a variable ${{ secrets.TOKEN_SECRET }}"

      - name: setup
        uses: actions/setup-node@v4
        with:
          node-version: '18'  # Specify the Node.js version to use